create schema contacts;

create table contacts.people (
name varchar(255),
surname varchar(255),
email varchar(255)
);

insert into contacts.people (name, surname, email) values 
('Ivan', 'Ivanov', 'ivanowow@gmail.com'), 
('Elena', 'Ivanova', 'lena2004@mail.ru'),
('Denis', 'Denisov', 'superprog@inbox.ru');

select * from contacts.people;
select name, surname from contacts.people;

update contacts.people 
set email = 'qwerty@com.mail'
where name = 'Elena';

delete from contacts.people 
where name = 'Elena';
--- task 2
create schema shop;
create table shop.products (
product_id int generated by default as identity primary key,
name varchar(255),
price int,
available boolean
);

create table shop.orders (
product_id int references shop.products(product_id),
count int,
date_of_order date 
);

insert into shop.products (name, price, available) values
('Sausage', 100, true),
('Bread', 40, false),
('Butter', 110, true),
('Eggs', 20, true);

insert into shop.orders (product_id, count, date_of_order) values
(1, 5, '1999-01-08'),
(3, 10, '2024-06-08'),
(4, 30, '2024-07-20');

select * from shop.products
where price < 50;

select * from shop.orders
where date_of_order >= '2003-01-01';

update shop.orders 
set count = 300
where product_id = 3;